logging:
  config: classpath:logback-spring.xml
multipart:
  maxFileSize: 100MB
  maxRequestSize: 100MB
  uploadTempDir: classpath:logs/
spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.web.servlet.MultipartAutoConfiguration
  http:
    encoding:
      charset: utf-8
      enabled: true
      force: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  profiles:
    active: sit
  server:
    tomcat:
      uri-encoding: UTF-8
  servlet:
    multipart:
      max-file-size: '100MB'
      max-request-size: '100MB'

zookeeper:
  address: ${SCAFFOLD_ZOOKEEPER_HOSTS:127.0.0.1:2181}

rocketmq:
  address: ${SCAFFOLD_ROCKETMQ_HOSTS:192.168.56.121:9876}

