---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xuexiao.
--- DateTime: 2022/3/13 上午9:00
--- Description:  获取分布式锁
local key = KEYS[1]
local requestId = KEYS[2]  --- 身份标识
local ttl = tonumber(KEYS[3])
local result = redis.call('setnx', key, requestId)
if result == 1 then
    --PEXPIRE:以毫秒的形式指定过期时间
    redis.call('pexpire', key, ttl)
else
    result = -1;
    -- 如果value相同，则认为是同一个线程的请求，则认为重入锁
    local value = redis.call('get', key)
    if (value == requestId) then
        result = 1; --可以重入的锁
        redis.call('pexpire', key, ttl)
    end
end
--  如果获取锁成功，则返回 1
return result